version: "3.5"

networks:
  proxy:
    driver: bridge

services:

  order:
    image: eddiriarte/php-8.1
    networks:
      - proxy
    volumes:
      - ./order-service:/var/www/html
    ports:
      - 8000:80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=order-service.local

  customer:
    image: eddiriarte/php-8.1
    networks:
      - proxy
    volumes:
      - ./customer-service:/var/www/html
    ports:
      - 8020:80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=customer-service.local

  payment:
    image: eddiriarte/php-8.1
    networks:
      - proxy
    volumes:
      - ./payment-service:/var/www/html
    ports:
      - 8040:80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=payment-service.local

  portal:
    image: eddiriarte/php-8.1
    networks:
      - proxy
    volumes:
      - ./web-portal:/var/www/html
    ports:
      - 8060:80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=web-portal.local

  slides:
    image: nginx
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - 3000:80
    environment:
      - VIRTUAL_HOST=consumer-driven-contract-testing.local
    networks:
      - proxy

  pact-broker:
    image: dius/pact-broker
    ports:
      - 4000:80
    volumes:
      - ./pact-broker.sqlite:/tmp/pact_broker.sqlite
    environment:
      - PACT_BROKER_DATABASE_ADAPTER=sqlite
      - PACT_BROKER_DATABASE_NAME=/tmp/pact_broker.sqlite
      - VIRTUAL_HOST=pact-broker.local
    networks:
      - proxy

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   userns: host
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - proxy
