version: "3.5"

networks:
  proxy:
    driver: bridge

services:

  order:
    image: eddiriarte/php-7.2
    networks:
      - proxy
    volumes:
      - ./order-service:/var/www/html
    ports:
      - 80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=order-service.local

  consumer:
    image: eddiriarte/php-7.2
    networks:
      - proxy
    volumes:
      - ./consumer-service:/var/www/html
    ports:
      - 80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=consumer-service.local
  
  payment:
    image: eddiriarte/php-7.2
    networks:
      - proxy
    volumes:
      - ./payment-service:/var/www/html
    ports:
      - 80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=payment-service.local

  portal:
    image: eddiriarte/php-7.2
    networks:
      - proxy
    volumes:
      - ./web-portal:/var/www/html
    ports:
      - 80
    working_dir: /var/www/html
    environment:
      - VIRTUAL_HOST=web-portal.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
  
  pact-broker:
    image: dius/pact-broker
    ports:
      - 80
    volumes:
      - ./pact-broker.sqlite:/tmp/pact_broker.sqlite
    environment:
      - PACT_BROKER_DATABASE_ADAPTER=sqlite
      - PACT_BROKER_DATABASE_NAME=/tmp/pact_broker.sqlite
      - VIRTUAL_HOST=pact-broker.local
    networks:
      - proxy
